/* File: my_libmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Apr 17 14:53:02 2019
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *my_lib_error;
static PyObject *my_lib_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(my_lib_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = my_lib_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = my_lib_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(get_rdf,GET_RDF)(int*,double*,string*,double*,double*,double*,int*,double*,double*);
extern void F_FUNC_US(init_cell,INIT_CELL)(double*,double*,double*,double*);
extern void F_FUNC_US(get_numberofreplicas,GET_NUMBEROFREPLICAS)(double*,double*,int*);
extern void F_FUNC(calcRij,CALCRIJ)(double*,double*,double*,double*,double*);
extern void F_FUNC(frac2cart,FRAC2CART)(double*,double*,double*);
extern void F_FUNC(matr3inv,MATR3INV)(double*,double*);
extern void F_FUNC(outprod3,OUTPROD3)(double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** get_rdf **********************************/
static char doc_f2py_rout_my_lib_get_rdf[] = "\
grid,vol = get_rdf(b,anames,r1,rmin,rmax,ngrid,[nn])\n\nWrapper for ``get_rdf``.\
\n\nParameters\n----------\n"
"b : input rank-1 array('d') with bounds (6)\n"
"anames : input rank-2 array('S') with bounds (nn,3)\n"
"r1 : input rank-1 array('d') with bounds (3 * nn)\n"
"rmin : input float\n"
"rmax : input float\n"
"ngrid : input int\n"
"\nOther Parameters\n----------------\n"
"nn : input int, optional\n    Default: shape(anames,0)\n"
"\nReturns\n-------\n"
"grid : rank-1 array('d') with bounds (ngrid)\n"
"vol : float";
/* extern void F_FUNC_US(get_rdf,GET_RDF)(int*,double*,string*,double*,double*,double*,int*,double*,double*); */
static PyObject *f2py_rout_my_lib_get_rdf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,string*,double*,double*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nn = 0;
  PyObject *nn_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  string *anames = NULL;
  npy_intp anames_Dims[2] = {-1, -1};
  const int anames_Rank = 2;
  PyArrayObject *capi_anames_tmp = NULL;
  int capi_anames_intent = 0;
  PyObject *anames_capi = Py_None;
  double *r1 = NULL;
  npy_intp r1_Dims[1] = {-1};
  const int r1_Rank = 1;
  PyArrayObject *capi_r1_tmp = NULL;
  int capi_r1_intent = 0;
  PyObject *r1_capi = Py_None;
  double rmin = 0;
  PyObject *rmin_capi = Py_None;
  double rmax = 0;
  PyObject *rmax_capi = Py_None;
  int ngrid = 0;
  PyObject *ngrid_capi = Py_None;
  double *grid = NULL;
  npy_intp grid_Dims[1] = {-1};
  const int grid_Rank = 1;
  PyArrayObject *capi_grid_tmp = NULL;
  int capi_grid_intent = 0;
  double vol = 0;
  static char *capi_kwlist[] = {"b","anames","r1","rmin","rmax","ngrid","nn",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:my_lib.get_rdf",\
    capi_kwlist,&b_capi,&anames_capi,&r1_capi,&rmin_capi,&rmax_capi,&ngrid_capi,&nn_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable b */
  b_Dims[0]=6;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `b' of my_lib.get_rdf to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable anames */
  anames_Dims[1]=3;
  capi_anames_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_anames_tmp = array_from_pyobj(NPY_CHAR,anames_Dims,anames_Rank,capi_anames_intent,anames_capi);
  if (capi_anames_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `anames' of my_lib.get_rdf to C/Fortran array" );
  } else {
    anames = (string *)(PyArray_DATA(capi_anames_tmp));

  /* Processing variable rmin */
    f2py_success = double_from_pyobj(&rmin,rmin_capi,"my_lib.get_rdf() 4th argument (rmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rmax */
    f2py_success = double_from_pyobj(&rmax,rmax_capi,"my_lib.get_rdf() 5th argument (rmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ngrid */
    f2py_success = int_from_pyobj(&ngrid,ngrid_capi,"my_lib.get_rdf() 6th argument (ngrid) can't be converted to int");
  if (f2py_success) {
  /* Processing variable vol */
  /* Processing variable nn */
  if (nn_capi == Py_None) nn = shape(anames,0); else
    f2py_success = int_from_pyobj(&nn,nn_capi,"my_lib.get_rdf() 1st keyword (nn) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(anames,0)==nn,"shape(anames,0)==nn","1st keyword nn","get_rdf:nn=%d",nn) {
  /* Processing variable r1 */
  r1_Dims[0]=3 * nn;
  capi_r1_intent |= F2PY_INTENT_IN;
  capi_r1_tmp = array_from_pyobj(NPY_DOUBLE,r1_Dims,r1_Rank,capi_r1_intent,r1_capi);
  if (capi_r1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 3rd argument `r1' of my_lib.get_rdf to C/Fortran array" );
  } else {
    r1 = (double *)(PyArray_DATA(capi_r1_tmp));

  /* Processing variable grid */
  grid_Dims[0]=ngrid;
  capi_grid_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_grid_tmp = array_from_pyobj(NPY_DOUBLE,grid_Dims,grid_Rank,capi_grid_intent,Py_None);
  if (capi_grid_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `grid' of my_lib.get_rdf to C/Fortran array" );
  } else {
    grid = (double *)(PyArray_DATA(capi_grid_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nn,b,anames,r1,&rmin,&rmax,&ngrid,grid,&vol);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nd",capi_grid_tmp,vol);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_grid_tmp == NULL) ... else of grid*/
  /* End of cleaning variable grid */
  if((PyObject *)capi_r1_tmp!=r1_capi) {
    Py_XDECREF(capi_r1_tmp); }
  }  /*if (capi_r1_tmp == NULL) ... else of r1*/
  /* End of cleaning variable r1 */
  } /*CHECKSCALAR(shape(anames,0)==nn)*/
  } /*if (f2py_success) of nn*/
  /* End of cleaning variable nn */
  /* End of cleaning variable vol */
  } /*if (f2py_success) of ngrid*/
  /* End of cleaning variable ngrid */
  } /*if (f2py_success) of rmax*/
  /* End of cleaning variable rmax */
  } /*if (f2py_success) of rmin*/
  /* End of cleaning variable rmin */
  if((PyObject *)capi_anames_tmp!=anames_capi) {
    Py_XDECREF(capi_anames_tmp); }
  }  /*if (capi_anames_tmp == NULL) ... else of anames*/
  /* End of cleaning variable anames */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of get_rdf *******************************/

/********************************* init_cell *********************************/
static char doc_f2py_rout_my_lib_init_cell[] = "\
rprimd,gprimd = init_cell(boxl,boxa)\n\nWrapper for ``init_cell``.\
\n\nParameters\n----------\n"
"boxl : input rank-1 array('d') with bounds (3)\n"
"boxa : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"rprimd : rank-2 array('d') with bounds (3,3)\n"
"gprimd : rank-2 array('d') with bounds (3,3)";
/* extern void F_FUNC_US(init_cell,INIT_CELL)(double*,double*,double*,double*); */
static PyObject *f2py_rout_my_lib_init_cell(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *boxl = NULL;
  npy_intp boxl_Dims[1] = {-1};
  const int boxl_Rank = 1;
  PyArrayObject *capi_boxl_tmp = NULL;
  int capi_boxl_intent = 0;
  PyObject *boxl_capi = Py_None;
  double *boxa = NULL;
  npy_intp boxa_Dims[1] = {-1};
  const int boxa_Rank = 1;
  PyArrayObject *capi_boxa_tmp = NULL;
  int capi_boxa_intent = 0;
  PyObject *boxa_capi = Py_None;
  double *rprimd = NULL;
  npy_intp rprimd_Dims[2] = {-1, -1};
  const int rprimd_Rank = 2;
  PyArrayObject *capi_rprimd_tmp = NULL;
  int capi_rprimd_intent = 0;
  double *gprimd = NULL;
  npy_intp gprimd_Dims[2] = {-1, -1};
  const int gprimd_Rank = 2;
  PyArrayObject *capi_gprimd_tmp = NULL;
  int capi_gprimd_intent = 0;
  static char *capi_kwlist[] = {"boxl","boxa",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:my_lib.init_cell",\
    capi_kwlist,&boxl_capi,&boxa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable boxl */
  boxl_Dims[0]=3;
  capi_boxl_intent |= F2PY_INTENT_IN;
  capi_boxl_tmp = array_from_pyobj(NPY_DOUBLE,boxl_Dims,boxl_Rank,capi_boxl_intent,boxl_capi);
  if (capi_boxl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `boxl' of my_lib.init_cell to C/Fortran array" );
  } else {
    boxl = (double *)(PyArray_DATA(capi_boxl_tmp));

  /* Processing variable boxa */
  boxa_Dims[0]=3;
  capi_boxa_intent |= F2PY_INTENT_IN;
  capi_boxa_tmp = array_from_pyobj(NPY_DOUBLE,boxa_Dims,boxa_Rank,capi_boxa_intent,boxa_capi);
  if (capi_boxa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `boxa' of my_lib.init_cell to C/Fortran array" );
  } else {
    boxa = (double *)(PyArray_DATA(capi_boxa_tmp));

  /* Processing variable rprimd */
  rprimd_Dims[0]=3,rprimd_Dims[1]=3;
  capi_rprimd_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_rprimd_tmp = array_from_pyobj(NPY_DOUBLE,rprimd_Dims,rprimd_Rank,capi_rprimd_intent,Py_None);
  if (capi_rprimd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `rprimd' of my_lib.init_cell to C/Fortran array" );
  } else {
    rprimd = (double *)(PyArray_DATA(capi_rprimd_tmp));

  /* Processing variable gprimd */
  gprimd_Dims[0]=3,gprimd_Dims[1]=3;
  capi_gprimd_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_gprimd_tmp = array_from_pyobj(NPY_DOUBLE,gprimd_Dims,gprimd_Rank,capi_gprimd_intent,Py_None);
  if (capi_gprimd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `gprimd' of my_lib.init_cell to C/Fortran array" );
  } else {
    gprimd = (double *)(PyArray_DATA(capi_gprimd_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(boxl,boxa,rprimd,gprimd);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_rprimd_tmp,capi_gprimd_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_gprimd_tmp == NULL) ... else of gprimd*/
  /* End of cleaning variable gprimd */
  }  /*if (capi_rprimd_tmp == NULL) ... else of rprimd*/
  /* End of cleaning variable rprimd */
  if((PyObject *)capi_boxa_tmp!=boxa_capi) {
    Py_XDECREF(capi_boxa_tmp); }
  }  /*if (capi_boxa_tmp == NULL) ... else of boxa*/
  /* End of cleaning variable boxa */
  if((PyObject *)capi_boxl_tmp!=boxl_capi) {
    Py_XDECREF(capi_boxl_tmp); }
  }  /*if (capi_boxl_tmp == NULL) ... else of boxl*/
  /* End of cleaning variable boxl */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of init_cell ******************************/

/**************************** get_numberofreplicas ****************************/
static char doc_f2py_rout_my_lib_get_numberofreplicas[] = "\
nxyz = get_numberofreplicas(rprimd,rc)\n\nWrapper for ``get_numberofreplicas``.\
\n\nParameters\n----------\n"
"rprimd : input rank-2 array('d') with bounds (3,3)\n"
"rc : input float\n"
"\nReturns\n-------\n"
"nxyz : rank-1 array('i') with bounds (3)";
/* extern void F_FUNC_US(get_numberofreplicas,GET_NUMBEROFREPLICAS)(double*,double*,int*); */
static PyObject *f2py_rout_my_lib_get_numberofreplicas(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *rprimd = NULL;
  npy_intp rprimd_Dims[2] = {-1, -1};
  const int rprimd_Rank = 2;
  PyArrayObject *capi_rprimd_tmp = NULL;
  int capi_rprimd_intent = 0;
  PyObject *rprimd_capi = Py_None;
  double rc = 0;
  PyObject *rc_capi = Py_None;
  int *nxyz = NULL;
  npy_intp nxyz_Dims[1] = {-1};
  const int nxyz_Rank = 1;
  PyArrayObject *capi_nxyz_tmp = NULL;
  int capi_nxyz_intent = 0;
  static char *capi_kwlist[] = {"rprimd","rc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:my_lib.get_numberofreplicas",\
    capi_kwlist,&rprimd_capi,&rc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rprimd */
  rprimd_Dims[0]=3,rprimd_Dims[1]=3;
  capi_rprimd_intent |= F2PY_INTENT_IN;
  capi_rprimd_tmp = array_from_pyobj(NPY_DOUBLE,rprimd_Dims,rprimd_Rank,capi_rprimd_intent,rprimd_capi);
  if (capi_rprimd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `rprimd' of my_lib.get_numberofreplicas to C/Fortran array" );
  } else {
    rprimd = (double *)(PyArray_DATA(capi_rprimd_tmp));

  /* Processing variable rc */
    f2py_success = double_from_pyobj(&rc,rc_capi,"my_lib.get_numberofreplicas() 2nd argument (rc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nxyz */
  nxyz_Dims[0]=3;
  capi_nxyz_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_nxyz_tmp = array_from_pyobj(NPY_INT,nxyz_Dims,nxyz_Rank,capi_nxyz_intent,Py_None);
  if (capi_nxyz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `nxyz' of my_lib.get_numberofreplicas to C/Fortran array" );
  } else {
    nxyz = (int *)(PyArray_DATA(capi_nxyz_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(rprimd,&rc,nxyz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_nxyz_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_nxyz_tmp == NULL) ... else of nxyz*/
  /* End of cleaning variable nxyz */
  } /*if (f2py_success) of rc*/
  /* End of cleaning variable rc */
  if((PyObject *)capi_rprimd_tmp!=rprimd_capi) {
    Py_XDECREF(capi_rprimd_tmp); }
  }  /*if (capi_rprimd_tmp == NULL) ... else of rprimd*/
  /* End of cleaning variable rprimd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of get_numberofreplicas ************************/

/********************************** calcRij **********************************/
static char doc_f2py_rout_my_lib_calcRij[] = "\
drsq = calcRij(boxl,boxa,rprimd,rij)\n\nWrapper for ``calcRij``.\
\n\nParameters\n----------\n"
"boxl : input rank-1 array('d') with bounds (3)\n"
"boxa : input rank-1 array('d') with bounds (3)\n"
"rprimd : input rank-2 array('d') with bounds (3,3)\n"
"rij : in/output rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"drsq : float";
/* extern void F_FUNC(calcRij,CALCRIJ)(double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_my_lib_calcRij(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *boxl = NULL;
  npy_intp boxl_Dims[1] = {-1};
  const int boxl_Rank = 1;
  PyArrayObject *capi_boxl_tmp = NULL;
  int capi_boxl_intent = 0;
  PyObject *boxl_capi = Py_None;
  double *boxa = NULL;
  npy_intp boxa_Dims[1] = {-1};
  const int boxa_Rank = 1;
  PyArrayObject *capi_boxa_tmp = NULL;
  int capi_boxa_intent = 0;
  PyObject *boxa_capi = Py_None;
  double *rprimd = NULL;
  npy_intp rprimd_Dims[2] = {-1, -1};
  const int rprimd_Rank = 2;
  PyArrayObject *capi_rprimd_tmp = NULL;
  int capi_rprimd_intent = 0;
  PyObject *rprimd_capi = Py_None;
  double *rij = NULL;
  npy_intp rij_Dims[1] = {-1};
  const int rij_Rank = 1;
  PyArrayObject *capi_rij_tmp = NULL;
  int capi_rij_intent = 0;
  PyObject *rij_capi = Py_None;
  double drsq = 0;
  static char *capi_kwlist[] = {"boxl","boxa","rprimd","rij",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:my_lib.calcRij",\
    capi_kwlist,&boxl_capi,&boxa_capi,&rprimd_capi,&rij_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable boxl */
  boxl_Dims[0]=3;
  capi_boxl_intent |= F2PY_INTENT_IN;
  capi_boxl_tmp = array_from_pyobj(NPY_DOUBLE,boxl_Dims,boxl_Rank,capi_boxl_intent,boxl_capi);
  if (capi_boxl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `boxl' of my_lib.calcRij to C/Fortran array" );
  } else {
    boxl = (double *)(PyArray_DATA(capi_boxl_tmp));

  /* Processing variable boxa */
  boxa_Dims[0]=3;
  capi_boxa_intent |= F2PY_INTENT_IN;
  capi_boxa_tmp = array_from_pyobj(NPY_DOUBLE,boxa_Dims,boxa_Rank,capi_boxa_intent,boxa_capi);
  if (capi_boxa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `boxa' of my_lib.calcRij to C/Fortran array" );
  } else {
    boxa = (double *)(PyArray_DATA(capi_boxa_tmp));

  /* Processing variable rprimd */
  rprimd_Dims[0]=3,rprimd_Dims[1]=3;
  capi_rprimd_intent |= F2PY_INTENT_IN;
  capi_rprimd_tmp = array_from_pyobj(NPY_DOUBLE,rprimd_Dims,rprimd_Rank,capi_rprimd_intent,rprimd_capi);
  if (capi_rprimd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 3rd argument `rprimd' of my_lib.calcRij to C/Fortran array" );
  } else {
    rprimd = (double *)(PyArray_DATA(capi_rprimd_tmp));

  /* Processing variable rij */
  rij_Dims[0]=3;
  capi_rij_intent |= F2PY_INTENT_INOUT;
  capi_rij_tmp = array_from_pyobj(NPY_DOUBLE,rij_Dims,rij_Rank,capi_rij_intent,rij_capi);
  if (capi_rij_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 4th argument `rij' of my_lib.calcRij to C/Fortran array" );
  } else {
    rij = (double *)(PyArray_DATA(capi_rij_tmp));

  /* Processing variable drsq */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(boxl,boxa,rprimd,rij,&drsq);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",drsq);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable drsq */
  if((PyObject *)capi_rij_tmp!=rij_capi) {
    Py_XDECREF(capi_rij_tmp); }
  }  /*if (capi_rij_tmp == NULL) ... else of rij*/
  /* End of cleaning variable rij */
  if((PyObject *)capi_rprimd_tmp!=rprimd_capi) {
    Py_XDECREF(capi_rprimd_tmp); }
  }  /*if (capi_rprimd_tmp == NULL) ... else of rprimd*/
  /* End of cleaning variable rprimd */
  if((PyObject *)capi_boxa_tmp!=boxa_capi) {
    Py_XDECREF(capi_boxa_tmp); }
  }  /*if (capi_boxa_tmp == NULL) ... else of boxa*/
  /* End of cleaning variable boxa */
  if((PyObject *)capi_boxl_tmp!=boxl_capi) {
    Py_XDECREF(capi_boxl_tmp); }
  }  /*if (capi_boxl_tmp == NULL) ... else of boxl*/
  /* End of cleaning variable boxl */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of calcRij *******************************/

/********************************* frac2cart *********************************/
static char doc_f2py_rout_my_lib_frac2cart[] = "\
r2 = frac2cart(rprimd,r1)\n\nWrapper for ``frac2cart``.\
\n\nParameters\n----------\n"
"rprimd : input rank-2 array('d') with bounds (3,3)\n"
"r1 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"r2 : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC(frac2cart,FRAC2CART)(double*,double*,double*); */
static PyObject *f2py_rout_my_lib_frac2cart(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *rprimd = NULL;
  npy_intp rprimd_Dims[2] = {-1, -1};
  const int rprimd_Rank = 2;
  PyArrayObject *capi_rprimd_tmp = NULL;
  int capi_rprimd_intent = 0;
  PyObject *rprimd_capi = Py_None;
  double *r1 = NULL;
  npy_intp r1_Dims[1] = {-1};
  const int r1_Rank = 1;
  PyArrayObject *capi_r1_tmp = NULL;
  int capi_r1_intent = 0;
  PyObject *r1_capi = Py_None;
  double *r2 = NULL;
  npy_intp r2_Dims[1] = {-1};
  const int r2_Rank = 1;
  PyArrayObject *capi_r2_tmp = NULL;
  int capi_r2_intent = 0;
  static char *capi_kwlist[] = {"rprimd","r1",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:my_lib.frac2cart",\
    capi_kwlist,&rprimd_capi,&r1_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rprimd */
  rprimd_Dims[0]=3,rprimd_Dims[1]=3;
  capi_rprimd_intent |= F2PY_INTENT_IN;
  capi_rprimd_tmp = array_from_pyobj(NPY_DOUBLE,rprimd_Dims,rprimd_Rank,capi_rprimd_intent,rprimd_capi);
  if (capi_rprimd_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `rprimd' of my_lib.frac2cart to C/Fortran array" );
  } else {
    rprimd = (double *)(PyArray_DATA(capi_rprimd_tmp));

  /* Processing variable r1 */
  r1_Dims[0]=3;
  capi_r1_intent |= F2PY_INTENT_IN;
  capi_r1_tmp = array_from_pyobj(NPY_DOUBLE,r1_Dims,r1_Rank,capi_r1_intent,r1_capi);
  if (capi_r1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `r1' of my_lib.frac2cart to C/Fortran array" );
  } else {
    r1 = (double *)(PyArray_DATA(capi_r1_tmp));

  /* Processing variable r2 */
  r2_Dims[0]=3;
  capi_r2_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_r2_tmp = array_from_pyobj(NPY_DOUBLE,r2_Dims,r2_Rank,capi_r2_intent,Py_None);
  if (capi_r2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `r2' of my_lib.frac2cart to C/Fortran array" );
  } else {
    r2 = (double *)(PyArray_DATA(capi_r2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(rprimd,r1,r2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_r2_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_r2_tmp == NULL) ... else of r2*/
  /* End of cleaning variable r2 */
  if((PyObject *)capi_r1_tmp!=r1_capi) {
    Py_XDECREF(capi_r1_tmp); }
  }  /*if (capi_r1_tmp == NULL) ... else of r1*/
  /* End of cleaning variable r1 */
  if((PyObject *)capi_rprimd_tmp!=rprimd_capi) {
    Py_XDECREF(capi_rprimd_tmp); }
  }  /*if (capi_rprimd_tmp == NULL) ... else of rprimd*/
  /* End of cleaning variable rprimd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of frac2cart ******************************/

/********************************** matr3inv **********************************/
static char doc_f2py_rout_my_lib_matr3inv[] = "\
matr3inv(aa,ait)\n\nWrapper for ``matr3inv``.\
\n\nParameters\n----------\n"
"aa : input rank-2 array('d') with bounds (3,3)\n"
"ait : input rank-2 array('d') with bounds (3,3)";
/* extern void F_FUNC(matr3inv,MATR3INV)(double*,double*); */
static PyObject *f2py_rout_my_lib_matr3inv(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *aa = NULL;
  npy_intp aa_Dims[2] = {-1, -1};
  const int aa_Rank = 2;
  PyArrayObject *capi_aa_tmp = NULL;
  int capi_aa_intent = 0;
  PyObject *aa_capi = Py_None;
  double *ait = NULL;
  npy_intp ait_Dims[2] = {-1, -1};
  const int ait_Rank = 2;
  PyArrayObject *capi_ait_tmp = NULL;
  int capi_ait_intent = 0;
  PyObject *ait_capi = Py_None;
  static char *capi_kwlist[] = {"aa","ait",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:my_lib.matr3inv",\
    capi_kwlist,&aa_capi,&ait_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable aa */
  aa_Dims[0]=3,aa_Dims[1]=3;
  capi_aa_intent |= F2PY_INTENT_IN;
  capi_aa_tmp = array_from_pyobj(NPY_DOUBLE,aa_Dims,aa_Rank,capi_aa_intent,aa_capi);
  if (capi_aa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `aa' of my_lib.matr3inv to C/Fortran array" );
  } else {
    aa = (double *)(PyArray_DATA(capi_aa_tmp));

  /* Processing variable ait */
  ait_Dims[0]=3,ait_Dims[1]=3;
  capi_ait_intent |= F2PY_INTENT_IN;
  capi_ait_tmp = array_from_pyobj(NPY_DOUBLE,ait_Dims,ait_Rank,capi_ait_intent,ait_capi);
  if (capi_ait_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `ait' of my_lib.matr3inv to C/Fortran array" );
  } else {
    ait = (double *)(PyArray_DATA(capi_ait_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(aa,ait);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_ait_tmp!=ait_capi) {
    Py_XDECREF(capi_ait_tmp); }
  }  /*if (capi_ait_tmp == NULL) ... else of ait*/
  /* End of cleaning variable ait */
  if((PyObject *)capi_aa_tmp!=aa_capi) {
    Py_XDECREF(capi_aa_tmp); }
  }  /*if (capi_aa_tmp == NULL) ... else of aa*/
  /* End of cleaning variable aa */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of matr3inv ******************************/

/********************************** outprod3 **********************************/
static char doc_f2py_rout_my_lib_outprod3[] = "\
a3 = outprod3(a1,a2)\n\nWrapper for ``outprod3``.\
\n\nParameters\n----------\n"
"a1 : input rank-1 array('d') with bounds (3)\n"
"a2 : input rank-1 array('d') with bounds (3)\n"
"\nReturns\n-------\n"
"a3 : rank-1 array('d') with bounds (3)";
/* extern void F_FUNC(outprod3,OUTPROD3)(double*,double*,double*); */
static PyObject *f2py_rout_my_lib_outprod3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *a1 = NULL;
  npy_intp a1_Dims[1] = {-1};
  const int a1_Rank = 1;
  PyArrayObject *capi_a1_tmp = NULL;
  int capi_a1_intent = 0;
  PyObject *a1_capi = Py_None;
  double *a2 = NULL;
  npy_intp a2_Dims[1] = {-1};
  const int a2_Rank = 1;
  PyArrayObject *capi_a2_tmp = NULL;
  int capi_a2_intent = 0;
  PyObject *a2_capi = Py_None;
  double *a3 = NULL;
  npy_intp a3_Dims[1] = {-1};
  const int a3_Rank = 1;
  PyArrayObject *capi_a3_tmp = NULL;
  int capi_a3_intent = 0;
  static char *capi_kwlist[] = {"a1","a2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:my_lib.outprod3",\
    capi_kwlist,&a1_capi,&a2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a1 */
  a1_Dims[0]=3;
  capi_a1_intent |= F2PY_INTENT_IN;
  capi_a1_tmp = array_from_pyobj(NPY_DOUBLE,a1_Dims,a1_Rank,capi_a1_intent,a1_capi);
  if (capi_a1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 1st argument `a1' of my_lib.outprod3 to C/Fortran array" );
  } else {
    a1 = (double *)(PyArray_DATA(capi_a1_tmp));

  /* Processing variable a2 */
  a2_Dims[0]=3;
  capi_a2_intent |= F2PY_INTENT_IN;
  capi_a2_tmp = array_from_pyobj(NPY_DOUBLE,a2_Dims,a2_Rank,capi_a2_intent,a2_capi);
  if (capi_a2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting 2nd argument `a2' of my_lib.outprod3 to C/Fortran array" );
  } else {
    a2 = (double *)(PyArray_DATA(capi_a2_tmp));

  /* Processing variable a3 */
  a3_Dims[0]=3;
  capi_a3_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_a3_tmp = array_from_pyobj(NPY_DOUBLE,a3_Dims,a3_Rank,capi_a3_intent,Py_None);
  if (capi_a3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(my_lib_error,"failed in converting hidden `a3' of my_lib.outprod3 to C/Fortran array" );
  } else {
    a3 = (double *)(PyArray_DATA(capi_a3_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(a1,a2,a3);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_a3_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_a3_tmp == NULL) ... else of a3*/
  /* End of cleaning variable a3 */
  if((PyObject *)capi_a2_tmp!=a2_capi) {
    Py_XDECREF(capi_a2_tmp); }
  }  /*if (capi_a2_tmp == NULL) ... else of a2*/
  /* End of cleaning variable a2 */
  if((PyObject *)capi_a1_tmp!=a1_capi) {
    Py_XDECREF(capi_a1_tmp); }
  }  /*if (capi_a1_tmp == NULL) ... else of a1*/
  /* End of cleaning variable a1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of outprod3 ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"get_rdf",-1,{{-1}},0,(char *)F_FUNC_US(get_rdf,GET_RDF),(f2py_init_func)f2py_rout_my_lib_get_rdf,doc_f2py_rout_my_lib_get_rdf},
  {"init_cell",-1,{{-1}},0,(char *)F_FUNC_US(init_cell,INIT_CELL),(f2py_init_func)f2py_rout_my_lib_init_cell,doc_f2py_rout_my_lib_init_cell},
  {"get_numberofreplicas",-1,{{-1}},0,(char *)F_FUNC_US(get_numberofreplicas,GET_NUMBEROFREPLICAS),(f2py_init_func)f2py_rout_my_lib_get_numberofreplicas,doc_f2py_rout_my_lib_get_numberofreplicas},
  {"calcRij",-1,{{-1}},0,(char *)F_FUNC(calcRij,CALCRIJ),(f2py_init_func)f2py_rout_my_lib_calcRij,doc_f2py_rout_my_lib_calcRij},
  {"frac2cart",-1,{{-1}},0,(char *)F_FUNC(frac2cart,FRAC2CART),(f2py_init_func)f2py_rout_my_lib_frac2cart,doc_f2py_rout_my_lib_frac2cart},
  {"matr3inv",-1,{{-1}},0,(char *)F_FUNC(matr3inv,MATR3INV),(f2py_init_func)f2py_rout_my_lib_matr3inv,doc_f2py_rout_my_lib_matr3inv},
  {"outprod3",-1,{{-1}},0,(char *)F_FUNC(outprod3,OUTPROD3),(f2py_init_func)f2py_rout_my_lib_outprod3,doc_f2py_rout_my_lib_outprod3},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "my_lib",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_my_lib(void) {
#else
#define RETVAL
PyMODINIT_FUNC initmy_lib(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = my_lib_module = PyModule_Create(&moduledef);
#else
  m = my_lib_module = Py_InitModule("my_lib", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module my_lib (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'my_lib' is auto-generated with f2py (version:2).\nFunctions:\n"
"  grid,vol = get_rdf(b,anames,r1,rmin,rmax,ngrid,nn=shape(anames,0))\n"
"  rprimd,gprimd = init_cell(boxl,boxa)\n"
"  nxyz = get_numberofreplicas(rprimd,rc)\n"
"  drsq = calcRij(boxl,boxa,rprimd,rij)\n"
"  r2 = frac2cart(rprimd,r1)\n"
"  matr3inv(aa,ait)\n"
"  a3 = outprod3(a1,a2)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  my_lib_error = PyErr_NewException ("my_lib.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));







/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"my_lib");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
